# Generated by Django 5.2.4 on 2025-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insureremaillog',
            old_name='client_name',
            new_name='insured_name',
        ),
        migrations.RemoveField(
            model_name='insureremaillog',
            name='usage_days',
        ),
        migrations.AddField(
            model_name='insureremaillog',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insureremaillog',
            name='police_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='insureremaillog',
            name='sender_name',
            field=models.CharField(default='Operations', max_length=200),
        ),
        migrations.AddField(
            model_name='insureremaillog',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insureremaillog',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insureremaillog',
            name='to_email',
            field=models.EmailField(default='chris@judkins.de', max_length=254),
        ),
    ]
