# Generated by Django 5.2.4 on 2025-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_rename_client_name_insureremaillog_insured_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureremaillog',
            name='to_email',
            field=models.EmailField(default='vertrag@zurich.com', max_length=254),
        ),
    ]
