# Generated by Django 5.2.4 on 2025-07-13 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
