# Generated by Django 5.2.4 on 2025-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_icon',
            field=models.CharField(default='restaurant', max_length=50),
        ),
    ]
