"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
from dotenv import load_dotenv
from pathlib import Path
import dj_database_url
import django_heroku
import pprint
from urllib.parse import urlparse
from django.db.backends.postgresql.base import DatabaseWrapper as PostgresWrapper
from django.db import connections
import sys


#region BASE SETTINGS
##################### /BASE SETTINGS #####################
# get BASE_DIR (always use this when referencing something in the project)
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(dotenv_path=BASE_DIR / '.env', override=True)


# OpenAI Key
OPENAI_KEY = os.getenv("OPENAI_KEY")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1")


ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()]

# define which user model to use for authentication
# This is necessary if you have a custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

##################### BASE SETTINGS #####################
#endregion



#region MEDIA FILES
######################## MEDIA FILES ########################


# S3 configuration
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = 'eu-central-1'  # or your actual region
AWS_QUERYSTRING_AUTH = False  # Make URLs public

# Optional
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None


USE_S3 = os.getenv("MEDIA_LOCAL", "False").lower() not in ("true", "1")

if USE_S3:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME"),
                "region_name": "eu-central-1",
                "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
                "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
                "default_acl": None,
                "querystring_auth": False,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://{os.getenv('AWS_STORAGE_BUCKET_NAME')}.s3.amazonaws.com/"
    print("[SETTINGS - MEDIA DEBUG] ✅ Using AWS S3")
    print("[SETTINGS - MEDIA DEBUG] MEDIA_URL:", MEDIA_URL)
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    MEDIA_URL = '/media/'
    print("[SETTINGS - MEDIA DEBUG] 🧪 Using local FileSystemStorage")
    print("[SETTINGS - MEDIA DEBUG] MEDIA_ROOT:", MEDIA_ROOT)


# STATIC FILES

# always use the local staticfiles app to serve static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]







######################## /MEDIA FILES ########################


#region APPLICATIONS/MIDDLEWARE/TEMPLATES
##################### /APPLICATIONS/MIDDLEWARE/TEMPLATES #####################
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'rest_framework',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',         # AWS S3
    'accounts',         # your user app
    'recipes',          # your core app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

##################### APPLICATIONS/MIDDLEWARE/TEMPLATES #####################
#enregion

#region DATABASE
##################### DATABASE #####################

# Database
# Detect local or Heroku
DATABASE_URL = os.getenv("DATABASE_URL")

# SET UP DATABASE DEPENDING ON WHETHER WE RE IN DEPLOYMENT OR DEVELOPMENT ENVIRONMENT
USE_HEROKU = "DYNO" in os.environ


if USE_HEROKU:
    print("🚀 Running in HEROKU MODE!")
    django_heroku.settings(locals(), databases=False)
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
else:
    print("🧪 Running in Local Dev Mode")
    raw_url = os.getenv("DATABASE_URL")
    if raw_url and "sslmode" not in raw_url:
        raw_url += "?sslmode=disable"
    DATABASES = {
        'default': dj_database_url.parse(raw_url)
    }


## DATABASE DEBUGGING
print("[SETTINGS - DATABASE DEBUG 1] Active Database URL:", os.getenv('DATABASE_URL'))
print("[SETTINGS - DATABASE DEBUG 2] Default Database Configuration:", DATABASES['default'])
##################### DATABASE #####################
#endregion


#region AUTHENTICATION & TIMEZONES
##################### AUTHENTICATION & TIMEZONES #####################
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
##################### /AUTHENTICATION & TIMEZONES #####################




#endregion

#region EMAIL SETTINGS
##################### EMAIL SETTINGS #####################
# Email backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 465))
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True").lower() in ("true", "1")
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# Heroku settings
#django_heroku.settings(locals())
##################### /EMAIL SET