# Generated by Django 5.2.4 on 2025-07-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_category_id',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='IngredientCategory',
        ),
    ]
