# Generated by Django 5.2.4 on 2025-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
