# Generated by Django 5.2.4 on 2025-07-16 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='linked_recipe',
            field=models.ForeignKey(blank=True, help_text='Optionally link this ingredient to another recipe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ingredients', to='recipes.recipe'),
        ),
    ]
